name: Staging Deployment

on:
  workflow_run:
    workflows: ["Commit Phase"]
    types:
      - completed
jobs:
  staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download frontend build artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-build-${{ github.event.workflow_run.id }}
          path: ./frontend-build
        
      - name: Deploy to Frontend Staging on Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=frontend-build --alias=staging 

      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_API_KEY }}
          github-token: ${{ secrets.REPO_TOKEN }}
          service-id: srv-cijkadtph6euh7k6e49g
          retries: 20
          wait: 16000
          sleep: 30000